# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb666afa7a2344da5d281b838a6849b910a555a1aaed2afabf443e0a0c127e0d7e0310bc11d82929502cbbe87e0a68b1e2e243902544f91537662eadb5ae5a3

test:
  secret_key_base: a4a471d4739ff3e70ff2e51503409fda9c8ba19a165d13e0975f83967d68d777a0c2d66f1f5a4c525b2ea5107db85fccea38d9d2bdb1edfa5610d3aad3b120bf

# Only a test repo so we can keep secrets.
production:
  secret_key_base: 27da10181e2750cb26d26d8fa615077b7fe8b49241ca5188a6ea94c5fa3f6bb3e6124b32ae89d4def3f268e17a5a360dd01931e3c7e6b0ae50f46fe9feb287bf
